# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.provision "file", source: "/Users/mariaventosa/Documents/_UDLAP/_10mo Semestre/REDES Y SERVIDORES/LAB/LAB03/server", destination: "$HOME"
    web.vm.box = "ubuntu/bionic64"
    web.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    web.vm.network "private_network", ip: "192.168.0.10"
    web.vm.provision "shell", inline: <<-SHELL
      echo "webserver" > /etc/hostname
      hostname -b webserver
      sudo apt-get update
      sudo apt-get install -y nodejs npm
      npm install express
      npm install socket.io
    SHELL
  end

  config.vm.define "clock" do |clock|
    clock.vm.box = "ubuntu/bionic64"
    clock.vm.provision "file", source: "/Users/mariaventosa/Documents/_UDLAP/_10mo Semestre/REDES Y SERVIDORES/LAB/LAB03/client", destination: "$HOME/client"
    clock.vm.network "forwarded_port", guest: 81, host: 7080, host_ip: "127.0.0.1"
    clock.vm.network "private_network", ip: "192.168.0.20"
    clock.vm.provision "shell", inline: <<-SHELL
      echo "clockserver" > /etc/hostname
      hostname -b clockserver
      sudo apt-get update
      sudo apt-get install -y nodejs npm
      npm init --yes react-app ./client
      cd client
      npm install
    SHELL
  end
end
